const DATA_IS_LOADING = "DATA_IS_LOADING";
const STORE_ADD_API_DATA = "STORE_ADD_API_DATA";
const DATA_HAS_ERROR_LOAD = "DATA_HAS_ERROR_LOAD";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
/*dataErrorLoad
const REQUEST_SUBREDDIT_JSON = "REQUEST_SUBREDDIT_JSON";
const RECEIVE_SUBREDDIT_JSON = "RECEIVE_SUBREDDIT_JSON";
*/
export default {
  DATA_IS_LOADING,
  STORE_ADD_API_DATA,
  DATA_HAS_ERROR_LOAD,
  SET_CURRENT_PAGE
  /* REQUEST_SUBREDDIT_POSTS,
  RECEIVE_SUBREDDIT_POSTS*/
};
